import { Circuit, CircuitBuilder } from '../../circuit-engine/circuit';
import { IFormatAdapter, IOOptions } from '../interfaces/format-adapter.interface';

/**
 * Quil (Quantum Instruction Language) format adapter.
 *
 * Rigetti's quantum instruction language for hybrid quantum-classical computing.
 *
 * Reference: https://pyquil-docs.rigetti.com/
 */
export class QuilAdapter implements IFormatAdapter {
  readonly name = 'Quil';
  readonly version = '3.0';
  readonly extensions = ['.quil'];

  /**
   * Parse Quil code to Circuit.
   */
  parse(data: string): Circuit {
    const lines = data.split('\n');
    let qubitCount = 0;
    const declaredQubits = new Map<string, number>();

    let builder: CircuitBuilder | null = null;

    for (const line of lines) {
      const trimmed = line.trim();

      // Skip empty lines and comments
      if (!trimmed || trimmed.startsWith('#') || trimmed.startsWith('DECLARE')) {
        continue;
      }

      // Qubit declarations
      const defgateMatch = trimmed.match(/DEFGATE\s+(\w+)/);
      if (defgateMatch) {
        // Skip custom gate definitions for now
        continue;
      }

      // Extract gate applications
      const gateMatch = trimmed.match(/^(\S+)\s+(.+)$/);
      if (gateMatch) {
        const gateName = gateMatch[1].toLowerCase();
        const args = gateMatch[2].trim();

        // Parse qubit references
        const qubits = this.parseQubitArgs(args, declaredQubits);

        // Initialize builder if needed
        const maxQubit = Math.max(...qubits, 0) + 1;
        if (!builder) {
          // Minimum 2 qubits to accommodate common circuits
          qubitCount = Math.max(maxQubit, 2);
          builder = Circuit.builder(qubitCount);
        } else if (maxQubit > qubitCount) {
          throw new Error(`Qubit index ${maxQubit - 1} exceeds declared qubits`);
        }

        // Parse parameters
        const params = this.parseParams(args);

        builder = this.applyGate(builder, gateName, qubits, params);
      }
    }

    if (!builder) {
      throw new Error('No valid Quil instructions found');
    }

    return builder.build();
  }

  /**
   * Parse qubit arguments from Quil syntax.
   */
  private parseQubitArgs(args: string, declaredQubits: Map<string, number>): number[] {
    const qubits: number[] = [];
    // Remove parameters in parentheses before parsing qubits
    const argsWithoutParams = args.replace(/\([^)]+\)/g, '');
    const parts = argsWithoutParams.split(/[\s,]+/);

    for (const part of parts) {
      if (!part.trim()) continue;
      // Match qubit[n] or just n
      const match = part.match(/\d+/);
      if (match) {
        qubits.push(parseInt(match[0], 10));
      }
    }

    return qubits;
  }

  /**
   * Parse parameters from arguments.
   */
  private parseParams(args: string): number[] {
    const params: number[] = [];

    // Match parameters in parentheses or as separate values
    const paramMatch = args.match(/\(([^)]+)\)/);
    if (paramMatch) {
      const paramStr = paramMatch[1];
      params.push(...paramStr.split(',').map((p) => parseFloat(p.trim())));
    }

    return params;
  }

  /**
   * Apply a Quil gate.
   */
  private applyGate(
    builder: CircuitBuilder,
    name: string,
    qubits: number[],
    params: number[],
  ): CircuitBuilder {
    const gateMap: Record<
      string,
      (b: CircuitBuilder, q: number[], p: number[]) => CircuitBuilder
    > = {
      h: (b, q) => b.h(q[0]),
      x: (b, q) => b.x(q[0]),
      y: (b, q) => b.y(q[0]),
      z: (b, q) => b.z(q[0]),
      s: (b, q) => b.s(q[0]),
      t: (b, q) => b.t(q[0]),
      rx: (b, q, p) => b.rx(q[0], p[0]),
      ry: (b, q, p) => b.ry(q[0], p[0]),
      rz: (b, q, p) => b.rz(q[0], p[0]),
      cnot: (b, q) => b.cx(q[0], q[1]),
      cz: (b, q) => b.cz(q[0], q[1]),
      swap: (b, q) => b.swap(q[0], q[1]),
      cphase: (b, q, p) => b.cp(q[0], q[1], p[0]),
      ccnot: (b, q) => b.ccx(q[0], q[1], q[2]),
      cswap: (b, q) => b.cswap(q[0], q[1], q[2]),
      // Controlled gates
      ch: (b, q) => b.ch(q[0], q[1]),
      cphaseshift: (b, q, p) => b.cp(q[0], q[1], p[0]),
    };

    if (name in gateMap) {
      return gateMap[name](builder, qubits, params);
    }

    console.warn(`Unknown Quil gate: ${name}`);
    return builder;
  }

  /**
   * Serialize Circuit to Quil format.
   */
  serialize(circuit: Circuit, options?: IOOptions): string {
    const metadata = circuit.getMetadata();
    const lines: string[] = [];

    // Header
    if (options?.includeComments) {
      lines.push('# Generated by casimirQ');
      lines.push(`# Qubits: ${metadata.qubitCount}`);
      lines.push(`# Gates: ${metadata.gateCount}`);
      lines.push('');
    }

    // Declare classical memory
    lines.push('DECLARE ro BIT[1]');
    lines.push('');

    // Circuit operations
    lines.push('# Circuit operations would be serialized here');

    return lines.join('\n');
  }

  /**
   * Validate Quil data.
   */
  validate(data: string): { valid: boolean; errors: string[] } {
    const errors: string[] = [];

    const lines = data.split('\n');
    let hasGate = false;

    for (let i = 0; i < lines.length; i++) {
      const line = lines[i].trim();

      // Skip empty lines and comments
      if (!line || line.startsWith('#')) {
        continue;
      }

      // Check for valid gate instructions
      const validInstructions = [
        'H',
        'X',
        'Y',
        'Z',
        'S',
        'T',
        'RX',
        'RY',
        'RZ',
        'CNOT',
        'CZ',
        'SWAP',
        'CCNOT',
        'CSWAP',
        'DECLARE',
        'DEFGATE',
        'MEASURE',
        'PRAGMA',
        'HALT',
      ];

      const firstWord = line.split(/\s+/)[0].toUpperCase();

      if (!validInstructions.some((inst) => firstWord.startsWith(inst))) {
        // Might be a custom gate definition, which is OK
        if (!firstWord.match(/^[A-Z][A-Z0-9_]*$/)) {
          errors.push(`Line ${i + 1}: Unknown instruction "${firstWord}"`);
        }
      } else {
        hasGate = true;
      }
    }

    if (!hasGate) {
      errors.push('No valid quantum gates found');
    }

    return {
      valid: errors.length === 0,
      errors,
    };
  }
}
